### ISSUE TITLE
Published to NuGet

### ISSUE THREAD

**Issue by Tallies** [aeagle/blazor-book#2]
Hi,

I can't seem to find this package on any NuGet package repository. Has this been published yet? 

Kind regards,
Charl

**Comment by aeagle** [comment]
Hi @Tallies.

No not yet. It's very WIP but I will see if I can get a beta package published.

**Comment by aeagle** [comment]
@Tallies I've published a pre-release package now. `BlazorBook`

**Comment by Tallies** [comment]
Thank you @aeagle.  Will test.
