### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by morpha1337** [aeagle/blazor-book#5]
Sorry But I couldnt figure out where the best place to send a message was.

I am after a grouping function in this library similar to what the original StoryBook has. I was going to just FORK the repo and add it myself but I noticed that exists in /DEV already.

I was wondering why that hasnt been merged yet?

**Comment by aeagle** [comment]
Hi @morpha1337. Grouping function has now been published under `v0.0.1-beta.3`
